spring:
  server:
    port: 8081

  datasource:
    url: jdbc:mysql://localhost:3306/it_cornner?useSSL=false
    username: root
    password: Jgd@9608
    driver-class-name: com.mysql.cj.jdbc.Driver

  #JPA Settings

  jpa:
    hibernate:
      ddl_auto:
        update
    show-sql: true